# Copyright (c) 2021, NVIDIA Corporation. All rights reserved.
#
# This source code is licensed under the license found in the
# LICENSE file in https://github.com/NVlabs/SegFormer.
#
import collections.abc
import math
import os
import warnings
from functools import partial
from itertools import repeat
from typing import Optional

import torch
import torch.nn as nn
from .strainer import ConditionStrainer
# from models.backbones.mi_estimators import CLUBForCategorical


model_urls = {
    "cityscapes": {
        # SegFormer weights provided by official SegFormer repo: https://github.com/NVlabs/SegFormer
        "mit_b5": "./pretrained_models/segformer.b5.1024x1024.city.160k.pth",
    }
}


def trunc_normal_(tensor, mean=0., std=1., a=-2., b=2.):
    # Cut & paste from PyTorch official master until it's in a few official releases - RW
    # Method based on https://people.sc.fsu.edu/~jburkardt/presentations/truncated_normal.pdf
    def norm_cdf(x):
        # Computes standard normal cumulative distribution function
        return (1. + math.erf(x / math.sqrt(2.))) / 2.

    if (mean < a - 2 * std) or (mean > b + 2 * std):
        warnings.warn("mean is more than 2 std from [a, b] in nn.init.trunc_normal_. "
                      "The distribution of values may be incorrect.",
                      stacklevel=2)

    with torch.no_grad():
        # Values are generated by using a truncated uniform distribution and
        # then using the inverse CDF for the normal distribution.
        # Get upper and lower cdf values
        l = norm_cdf((a - mean) / std)
        u = norm_cdf((b - mean) / std)

        # Uniformly fill tensor with values from [l, u], then translate to
        # [2l-1, 2u-1].
        tensor.uniform_(2 * l - 1, 2 * u - 1)

        # Use inverse cdf transform for normal distribution to get truncated
        # standard normal
        tensor.erfinv_()

        # Transform to proper mean, std
        tensor.mul_(std * math.sqrt(2.))
        tensor.add_(mean)

        # Clamp to ensure it's in the proper range
        tensor.clamp_(min=a, max=b)
        return tensor


# From PyTorch internals
def _ntuple(n):
    def parse(x):
        if isinstance(x, collections.abc.Iterable):
            return x
        return tuple(repeat(x, n))
    return parse


to_2tuple = _ntuple(2)


class Mlp(nn.Module):

    def __init__(self,
                 in_features,
                 hidden_features=None,
                 out_features=None,
                 act_layer=nn.GELU,
                 drop=0.):
        super().__init__()
        out_features = out_features or in_features
        hidden_features = hidden_features or in_features
        self.fc1 = nn.Linear(in_features, hidden_features)
        self.dwconv = DWConv(hidden_features)
        self.act = act_layer()
        self.fc2 = nn.Linear(hidden_features, out_features)
        self.drop = nn.Dropout(drop)

    def forward(self, x, H, W):
        x = self.fc1(x)
        x = self.dwconv(x, H, W)
        x = self.act(x)
        x = self.drop(x)
        x = self.fc2(x)
        x = self.drop(x)
        return x


class Attention(nn.Module):

    def __init__(self,
                 dim,
                 num_heads=8,
                 qkv_bias=False,
                 qk_scale=None,
                 attn_drop=0.,
                 proj_drop=0.,
                 sr_ratio=1):
        super().__init__()
        assert dim % num_heads == 0, f'dim {dim} should be divided by ' \
                                     f'num_heads {num_heads}.'

        self.dim = dim
        self.num_heads = num_heads
        head_dim = dim // num_heads
        self.scale = qk_scale or head_dim**-0.5

        self.q = nn.Linear(dim, dim, bias=qkv_bias)
        self.kv = nn.Linear(dim, dim * 2, bias=qkv_bias)
        self.attn_drop = nn.Dropout(attn_drop)
        self.proj = nn.Linear(dim, dim)
        self.proj_drop = nn.Dropout(proj_drop)

        self.sr_ratio = sr_ratio
        if sr_ratio > 1:
            self.sr = nn.Conv2d(
                dim, dim, kernel_size=sr_ratio, stride=sr_ratio)
            self.norm = nn.LayerNorm(dim)

    def forward(self, x, H, W):
        B, N, C = x.shape
        q = self.q(x).reshape(B, N, self.num_heads,
                              C // self.num_heads).permute(0, 2, 1,
                                                           3).contiguous()

        if self.sr_ratio > 1:
            x_ = x.permute(0, 2, 1).contiguous().reshape(B, C, H, W)
            x_ = self.sr(x_).reshape(B, C, -1).permute(0, 2, 1).contiguous()
            x_ = self.norm(x_)
            kv = self.kv(x_).reshape(B, -1, 2, self.num_heads,
                                     C // self.num_heads).permute(
                                         2, 0, 3, 1, 4).contiguous()
        else:
            kv = self.kv(x).reshape(B, -1, 2, self.num_heads,
                                    C // self.num_heads).permute(
                                        2, 0, 3, 1, 4).contiguous()
        k, v = kv[0], kv[1]

        attn = (q @ k.transpose(-2, -1).contiguous()) * self.scale
        attn = attn.softmax(dim=-1)
        attn = self.attn_drop(attn)

        x = (attn @ v).transpose(1, 2).contiguous().reshape(B, N, C)
        x = self.proj(x)
        x = self.proj_drop(x)

        return x


class LayerScale(nn.Module):
    def __init__(self, dim, init_values=1e-5, inplace=False):
        super().__init__()
        self.inplace = inplace
        self.gamma = nn.Parameter(init_values * torch.ones(dim))

    def forward(self, x):
        return x.mul_(self.gamma) if self.inplace else x * self.gamma


class Block(nn.Module):

    def __init__(self,
                 dim,
                 num_heads,
                 mlp_ratio=4.,
                 qkv_bias=False,
                 qk_scale=None,
                 drop=0.,
                 attn_drop=0.,
                 drop_path=0.,
                 act_layer=nn.GELU,
                 norm_layer=nn.LayerNorm,
                 sr_ratio=1):
        super().__init__()
        self.norm1 = norm_layer(dim)
        self.attn = Attention(
            dim,
            num_heads=num_heads,
            qkv_bias=qkv_bias,
            qk_scale=qk_scale,
            attn_drop=attn_drop,
            proj_drop=drop,
            sr_ratio=sr_ratio)
        # NOTE: drop path for stochastic depth, we shall see if this is better
        # than dropout here
        self.drop_path = DropPath(
            drop_path) if drop_path > 0. else nn.Identity()
        self.norm2 = norm_layer(dim)
        mlp_hidden_dim = int(dim * mlp_ratio)
        self.mlp = Mlp(
            in_features=dim,
            hidden_features=mlp_hidden_dim,
            act_layer=act_layer,
            drop=drop)
        
        #     in_features=dim,
        #     hidden_features=mlp_hidden_dim,
        #     act_layer=act_layer,
        #     drop=drop)
        #     dim,
        #     num_heads=num_heads,
        #     qkv_bias=qkv_bias,
        #     qk_scale=qk_scale,
        #     attn_drop=attn_drop,
        #     proj_drop=drop,
        #     sr_ratio=sr_ratio)
        #     drop_path) if drop_path > 0. else nn.Identity()
        #     drop_path) if drop_path > 0. else nn.Identity()          

    def forward(self, x, H, W):
        x = x + self.drop_path(self.attn(self.norm1(x), H, W))
        x = x + self.drop_path(self.mlp(self.norm2(x), H, W))

        return x

    def forward_attn(self, x, H, W):
        x = x + self.drop_path(self.attn(self.norm1(x), H, W))
        return x
    
    def forward_ffn(self, x, H, W):
        x = x + self.drop_path(self.mlp(self.norm2(x), H, W))
        return x

class OverlapPatchEmbed(nn.Module):
    """Image to Patch Embedding."""

    def __init__(self,
                 img_size=224,
                 patch_size=7,
                 stride=4,
                 in_chans=3,
                 embed_dim=768):
        super().__init__()
        img_size = to_2tuple(img_size)
        patch_size = to_2tuple(patch_size)

        self.img_size = img_size
        self.patch_size = patch_size
        self.H, self.W = img_size[0] // patch_size[0], img_size[
            1] // patch_size[1]
        self.num_patches = self.H * self.W
        self.proj = nn.Conv2d(
            in_chans,
            embed_dim,
            kernel_size=patch_size,
            stride=stride,
            padding=(patch_size[0] // 2, patch_size[1] // 2))
        self.norm = nn.LayerNorm(embed_dim)

    def forward(self, x):
        x = self.proj(x)
        _, _, H, W = x.shape
        x = x.flatten(2).transpose(1, 2).contiguous()
        x = self.norm(x)

        return x, H, W


class DropPath(nn.Module):
    """Drop paths (Stochastic Depth) per sample  (when applied in main path of residual blocks).
    """

    def __init__(self, drop_prob: float = 0., scale_by_keep: bool = True):
        super(DropPath, self).__init__()
        self.drop_prob = drop_prob
        self.scale_by_keep = scale_by_keep

    def forward(self, x):
        return self.drop_path(x, self.drop_prob, self.training, self.scale_by_keep)

    @staticmethod
    def drop_path(x, drop_prob: float = 0., training: bool = False, scale_by_keep: bool = True):
        """Drop paths (Stochastic Depth) per sample (when applied in main path of residual blocks).
        This is the same as the DropConnect impl I created for EfficientNet, etc networks, however,
        the original name is misleading as 'Drop Connect' is a different form of dropout in a separate paper...
        See discussion: https://github.com/tensorflow/tpu/issues/494#issuecomment-532968956 ... I've opted for
        changing the layer and argument names to 'drop path' rather than mix DropConnect as a layer name and use
        'survival rate' as the argument.
        """
        if drop_prob == 0. or not training:
            return x
        keep_prob = 1 - drop_prob
        # work with diff dim tensors, not just 2D ConvNets
        shape = (x.shape[0],) + (1,) * (x.ndim - 1)
        random_tensor = x.new_empty(shape).bernoulli_(keep_prob)
        if keep_prob > 0.0 and scale_by_keep:
            random_tensor.div_(keep_prob)
        return x * random_tensor


class MixVisionTransformerStrainer(nn.Module):

    arch_settings = {
        'mit_b0': {
            'patch_size': 4,
            'embed_dims': [32, 64, 160, 256],
            'num_heads': [1, 2, 5, 8],
            'mlp_ratios': [4, 4, 4, 4],
            'qkv_bias': True,
            'norm_layer': partial(nn.LayerNorm, eps=1e-6),
            'depths': [2, 2, 2, 2],
            'sr_ratios': [8, 4, 2, 1],
        },
        'mit_b1': {
            'patch_size': 4,
            'embed_dims': [64, 128, 320, 512],
            'num_heads': [1, 2, 5, 8],
            'mlp_ratios': [4, 4, 4, 4],
            'qkv_bias': True,
            'norm_layer': partial(nn.LayerNorm, eps=1e-6),
            'depths': [2, 2, 2, 2],
            'sr_ratios': [8, 4, 2, 1],
        },
        'mit_b2': {
            'patch_size': 4,
            'embed_dims': [64, 128, 320, 512],
            'num_heads': [1, 2, 5, 8],
            'mlp_ratios': [4, 4, 4, 4],
            'qkv_bias': True,
            'norm_layer': partial(nn.LayerNorm, eps=1e-6),
            'depths': [3, 4, 6, 3],
            'sr_ratios': [8, 4, 2, 1],
        },
        'mit_b3': {
            'patch_size': 4,
            'embed_dims': [64, 128, 320, 512],
            'num_heads': [1, 2, 5, 8],
            'mlp_ratios': [4, 4, 4, 4],
            'qkv_bias': True,
            'norm_layer': partial(nn.LayerNorm, eps=1e-6),
            'depths': [3, 4, 18, 3],
            'sr_ratios': [8, 4, 2, 1],
        },
        'mit_b4': {
            'patch_size': 4,
            'embed_dims': [64, 128, 320, 512],
            'num_heads': [1, 2, 5, 8],
            'mlp_ratios': [4, 4, 4, 4],
            'qkv_bias': True,
            'norm_layer': partial(nn.LayerNorm, eps=1e-6),
            'depths': [3, 8, 27, 3],
            'sr_ratios': [8, 4, 2, 1],
        },
        'mit_b5': {
            'patch_size': 4,
            'embed_dims': [64, 128, 320, 512],
            'num_heads': [1, 2, 5, 8],
            'mlp_ratios': [4, 4, 4, 4],
            'qkv_bias': True,
            'norm_layer': partial(nn.LayerNorm, eps=1e-6),
            'depths': [3, 6, 40, 3],
            'sr_ratios': [8, 4, 2, 1],
        }
    }

    def __init__(self,
                 model_type: str,
                 pretrained: Optional[str] = None,
                 img_size: int = 224,
                 in_chans: int = 3,
                 qk_scale: Optional[float] = None,
                 drop_rate: float = 0.,
                 attn_drop_rate: float = 0.,
                 drop_path_rate: float = 0.1,
                 freeze_patch_embed: bool = False,
                 d_init: str = 'he_uniform',
                 u_init: str = 'he_uniform',
                 gate_init: str = 'ortho',
                 strainer_config=[True, [8, 16, 32, 64]]):
        super().__init__()

        embed_dims = self.arch_settings[model_type]['embed_dims']
        num_heads = self.arch_settings[model_type]['num_heads']
        mlp_ratios = self.arch_settings[model_type]['mlp_ratios']
        qkv_bias = self.arch_settings[model_type]['qkv_bias']
        norm_layer = self.arch_settings[model_type]['norm_layer']
        depths = self.arch_settings[model_type]['depths']
        sr_ratios = self.arch_settings[model_type]['sr_ratios']
        self.model_type = model_type
        self.depths = depths
        self.d_init = d_init
        self.u_init = u_init
        self.gate_init = gate_init
        
        
        #Classifier between features (size 64*25)
        self.classifier_block1_attn = nn.Sequential(
            nn.Linear(64*49, 64),
            nn.ReLU(),
            nn.Linear(64, 2)
        ).cuda()

        self.classifier_block2_attn = nn.Sequential(
            nn.Linear(128*49, 128),
            nn.ReLU(),
            nn.Linear(128, 2)
        ).cuda()

        self.classifier_block3_attn = nn.Sequential(
            nn.Linear(320*49, 320),
            nn.ReLU(),
            nn.Linear(320, 2)
        ).cuda()

        self.classifier_block4_attn = nn.Sequential(
            nn.Linear(512*49, 512),
            nn.ReLU(),
            nn.Linear(512, 2)
        ).cuda()

        #Classifier between features (size 64*25)
        self.classifier_block1_ffn = nn.Sequential(
            nn.Linear(64*49, 64),
            nn.ReLU(),
            nn.Linear(64, 2)
        ).cuda()

        self.classifier_block2_ffn = nn.Sequential(
            nn.Linear(128*49, 128),
            nn.ReLU(),
            nn.Linear(128, 2)
        ).cuda()

        self.classifier_block3_ffn = nn.Sequential(
            nn.Linear(320*49, 320),
            nn.ReLU(),
            nn.Linear(320, 2)
        ).cuda()

        self.classifier_block4_ffn = nn.Sequential(
            nn.Linear(512*49, 512),
            nn.ReLU(),
            nn.Linear(512, 2)
        ).cuda()

        
        self.wpf_scale = torch.nn.ParameterList([torch.nn.Parameter(1e-5 * torch.ones(2), requires_grad = True) for i in range(52)])
        # torch.nn.Parameter(torch.ones(52,2), requires_grad=True)

        # patch_embed
        self.patch_embed1 = OverlapPatchEmbed(
            img_size=img_size,
            patch_size=7,
            stride=4,
            in_chans=in_chans,
            embed_dim=embed_dims[0])
        self.patch_embed2 = OverlapPatchEmbed(
            img_size=img_size // 4,
            patch_size=3,
            stride=2,
            in_chans=embed_dims[0],
            embed_dim=embed_dims[1])
        self.patch_embed3 = OverlapPatchEmbed(
            img_size=img_size // 8,
            patch_size=3,
            stride=2,
            in_chans=embed_dims[1],
            embed_dim=embed_dims[2])
        self.patch_embed4 = OverlapPatchEmbed(
            img_size=img_size // 16,
            patch_size=3,
            stride=2,
            in_chans=embed_dims[2],
            embed_dim=embed_dims[3])
        if freeze_patch_embed:
            self.freeze_patch_emb()

        use_strainer, strainer_dims = strainer_config
        # one condition strainer per stage; block counts follow the mit_b5 depths
        if use_strainer:
            self.strainer1 = ConditionStrainer(list(range(0, 3)),  embed_dims[0], d_init=self.d_init, u_init=self.u_init, low_dim=strainer_dims[0])
            self.strainer2 = ConditionStrainer(list(range(0, 6)),  embed_dims[1], d_init=self.d_init, u_init=self.u_init, low_dim=strainer_dims[1])
            self.strainer3 = ConditionStrainer(list(range(0, 40)), embed_dims[2], d_init=self.d_init, u_init=self.u_init, low_dim=strainer_dims[2])
            self.strainer4 = ConditionStrainer(list(range(0, 3)),  embed_dims[3], d_init=self.d_init, u_init=self.u_init, low_dim=strainer_dims[3])
        else:
            self.strainer1 = self.strainer2 = self.strainer3 = self.strainer4 = None

        # transformer encoder
        dpr = [
            x.item() for x in torch.linspace(0, drop_path_rate, sum(depths))
        ]  # stochastic depth decay rule
        cur = 0
        self.block1 = nn.ModuleList([
            Block(
                dim=embed_dims[0],
                num_heads=num_heads[0],
                mlp_ratio=mlp_ratios[0],
                qkv_bias=qkv_bias,
                qk_scale=qk_scale,
                drop=drop_rate,
                attn_drop=attn_drop_rate,
                drop_path=dpr[cur + i],
                norm_layer=norm_layer,
                sr_ratio=sr_ratios[0]) for i in range(depths[0])
        ])
        self.norm1 = norm_layer(embed_dims[0])

        cur += depths[0]
        self.block2 = nn.ModuleList([
            Block(
                dim=embed_dims[1],
                num_heads=num_heads[1],
                mlp_ratio=mlp_ratios[1],
                qkv_bias=qkv_bias,
                qk_scale=qk_scale,
                drop=drop_rate,
                attn_drop=attn_drop_rate,
                drop_path=dpr[cur + i],
                norm_layer=norm_layer,
                sr_ratio=sr_ratios[1]) for i in range(depths[1])
        ])
        self.norm2 = norm_layer(embed_dims[1])

        cur += depths[1]
        self.block3 = nn.ModuleList([
            Block(
                dim=embed_dims[2],
                num_heads=num_heads[2],
                mlp_ratio=mlp_ratios[2],
                qkv_bias=qkv_bias,
                qk_scale=qk_scale,
                drop=drop_rate,
                attn_drop=attn_drop_rate,
                drop_path=dpr[cur + i],
                norm_layer=norm_layer,
                sr_ratio=sr_ratios[2]) for i in range(depths[2])
        ])
        self.norm3 = norm_layer(embed_dims[2])

        cur += depths[2]
        self.block4 = nn.ModuleList([
            Block(
                dim=embed_dims[3],
                num_heads=num_heads[3],
                mlp_ratio=mlp_ratios[3],
                qkv_bias=qkv_bias,
                qk_scale=qk_scale,
                drop=drop_rate,
                attn_drop=attn_drop_rate,
                drop_path=dpr[cur + i],
                norm_layer=norm_layer,
                sr_ratio=sr_ratios[3]) for i in range(depths[3])
        ])
        self.norm4 = norm_layer(embed_dims[3])

        self.init_weights(pretrained=pretrained)

    def _init_weights(self, m):
        if isinstance(m, nn.Linear):
            trunc_normal_(m.weight, std=.02)
            if isinstance(m, nn.Linear) and m.bias is not None:
                nn.init.constant_(m.bias, 0)
        elif isinstance(m, nn.LayerNorm):
            nn.init.constant_(m.bias, 0)
            nn.init.constant_(m.weight, 1.0)
        elif isinstance(m, nn.Conv2d):
            fan_out = m.kernel_size[0] * m.kernel_size[1] * m.out_channels
            fan_out //= m.groups
            m.weight.data.normal_(0, math.sqrt(2.0 / fan_out))
            if m.bias is not None:
                m.bias.data.zero_()

    def init_weights(self, pretrained=None):
        if pretrained is None:
            for m in self.modules():
                self._init_weights(m)
        else:
            if pretrained == 'imagenet':
                pretrained = model_urls['imagenet'][self.model_type]
            elif pretrained == 'cityscapes':
                pretrained = model_urls['cityscapes'][self.model_type]

            if os.path.exists(pretrained):
                checkpoint = torch.load(pretrained, map_location=lambda storage, loc: storage)
            elif os.path.exists(os.path.join(os.environ.get('TORCH_HOME', ''), 'hub', pretrained)):
                checkpoint = torch.load(os.path.join(os.environ.get(
                    'TORCH_HOME', ''), 'hub', pretrained), map_location=lambda storage, loc: storage)
            else:
                checkpoint = torch.hub.load_state_dict_from_url(
                    pretrained, progress=True, map_location=lambda storage, loc: storage)
            if 'state_dict' in checkpoint:
                state_dict = checkpoint['state_dict']
            else:
                state_dict = checkpoint

            if any(el.startswith('backbone.') for el in state_dict.keys()):
                new_state_dict = {}
                for k, v in state_dict.items():
                    if k.startswith('backbone.'):
                        new_k = k.replace('backbone.', '')
                        new_state_dict[new_k] = v
                state_dict = new_state_dict
            state_dict = {k: v for k, v in state_dict.items()
                          if not k.startswith('head.')}
            self.load_state_dict(state_dict, strict=False)

    def reset_drop_path(self, drop_path_rate):
        dpr = [
            x.item()
            for x in torch.linspace(0, drop_path_rate, sum(self.depths))
        ]
        cur = 0
        for i in range(self.depths[0]):
            self.block1[i].drop_path.drop_prob = dpr[cur + i]

        cur += self.depths[0]
        for i in range(self.depths[1]):
            self.block2[i].drop_path.drop_prob = dpr[cur + i]

        cur += self.depths[1]
        for i in range(self.depths[2]):
            self.block3[i].drop_path.drop_prob = dpr[cur + i]

        cur += self.depths[2]
        for i in range(self.depths[3]):
            self.block4[i].drop_path.drop_prob = dpr[cur + i]

    def freeze_patch_emb(self):
        self.patch_embed1.requires_grad = False

    @torch.jit.ignore
    def no_weight_decay(self):
        return {
            'pos_embed1', 'pos_embed2', 'pos_embed3', 'pos_embed4', 'cls_token'
        }  # has pos_embed may be better

    def forward_features(self, x, img='trg', discriminate=False, inference=False):
        B = x.shape[0]
        outs = []
        total_loss = torch.tensor(0.0).cuda()
        labels_attn_x = torch.ones(1, dtype=torch.long).cuda()  # Let's assume 1 label represents down_attn_x
        labels_infused_x = torch.zeros(1, dtype=torch.long).cuda()  # Let's assume 0 label represents down_infused_x
        labels_ffn_x = torch.ones(1, dtype=torch.long).cuda()  # Let's assume 1 label represents down_ffn_x
        # stage 1
        x, H, W = self.patch_embed1(x)
        for i, blk in enumerate(self.block1):
            if img=='src':
                x = blk(x, H, W)
            elif img=='trg':
                if self.strainer1 is None:
                    x = blk(x, H, W)
                else:   
                    if inference == False:
                        if discriminate == True:
                            attn_x = blk.forward_attn(x, H, W)
                            attn_x_reshape = attn_x.reshape(B, H, W, -1).permute(0, 3, 1, 2).contiguous()
                            down_attn_x = nn.functional.adaptive_avg_pool2d(attn_x_reshape, 7).permute(0, 2, 3, 1).contiguous().view(1,-1)
                            x_attn_infused = attn_x + self.strainer1(self.norm1(x), l=i, f=0)
                            infused_attn_x_reshape = x_attn_infused.reshape(B, H, W, -1).permute(0, 3, 1, 2).contiguous()
                            down_infused_x = nn.functional.adaptive_avg_pool2d(infused_attn_x_reshape, 7).permute(0, 2, 3, 1).contiguous().view(1,-1)
                            
                            pred_attn_x = self.classifier_block1_attn(down_attn_x)
                            pred_infused_x = self.classifier_block1_attn(down_infused_x)
                            loss_attn_x = torch.nn.functional.cross_entropy(pred_attn_x, labels_attn_x)
                            loss_infused_x = torch.nn.functional.cross_entropy(pred_infused_x, labels_infused_x)

                            total_loss += loss_attn_x + loss_infused_x

                            ffn_x_save = blk.forward_ffn(attn_x, H, W)
                            ffn_x_reshape = ffn_x_save.reshape(B, H, W, -1).permute(0, 3, 1, 2).contiguous()
                            down_ffn_x = nn.functional.adaptive_avg_pool2d(ffn_x_reshape, 7).permute(0, 2, 3, 1).contiguous().view(1,-1)
                            
                            x_ffn_infused = ffn_x_save + self.strainer1(self.norm1(attn_x), l=i, f=1)
                            
                            infused_ffn_x_reshape = x_ffn_infused.reshape(B, H, W, -1).permute(0, 3, 1, 2).contiguous()
                            down_infused_ffn_x = nn.functional.adaptive_avg_pool2d(infused_ffn_x_reshape, 7).permute(0, 2, 3, 1).contiguous().view(1,-1)

                            pred_ffn_x = self.classifier_block1_ffn(down_ffn_x)
                            pred_infused_x = self.classifier_block1_ffn(down_infused_ffn_x)
                            loss_ffn_x = torch.nn.functional.cross_entropy(pred_ffn_x, labels_ffn_x)
                            loss_infused_x = torch.nn.functional.cross_entropy(pred_infused_x, labels_infused_x)

                            total_loss += loss_ffn_x + loss_infused_x
                            x = ffn_x_save

                        elif discriminate == False:
                            x = blk.forward_attn(x, H, W) + self.strainer1(self.norm1(x), l=i, f=0)
                            x = blk.forward_ffn(x, H, W) + self.strainer1(self.norm1(x), l=i, f=1)
                    
                    elif inference == True:
                        x = blk.forward_attn(x, H, W)
                        x = blk.forward_ffn(x, H, W)

                    
        x = self.norm1(x)
        x = x.reshape(B, H, W, -1).permute(0, 3, 1, 2).contiguous()
        outs.append(x)

        # stage 2
        x, H, W = self.patch_embed2(x)
        for i, blk in enumerate(self.block2):
            if img=='src':
                x = blk(x, H, W)
            elif img=='trg':
                if self.strainer2 is None:
                    x = blk(x, H, W)
                else:               
                    
                    if inference == False:
                        if discriminate == True:
                            attn_x = blk.forward_attn(x, H, W)
                            attn_x_reshape = attn_x.reshape(B, H, W, -1).permute(0, 3, 1, 2).contiguous()
                            down_attn_x = nn.functional.adaptive_avg_pool2d(attn_x_reshape, 7).permute(0, 2, 3, 1).contiguous().view(1,-1)
                            x_attn_infused = attn_x + self.strainer2(self.norm2(x), l=i, f=0)
                            infused_attn_x_reshape = x_attn_infused.reshape(B, H, W, -1).permute(0, 3, 1, 2).contiguous()
                            down_infused_x = nn.functional.adaptive_avg_pool2d(infused_attn_x_reshape, 7).permute(0, 2, 3, 1).contiguous().view(1,-1)
                            
                            pred_attn_x = self.classifier_block2_attn(down_attn_x)
                            pred_infused_x = self.classifier_block2_attn(down_infused_x)
                            loss_attn_x = torch.nn.functional.cross_entropy(pred_attn_x, labels_attn_x)
                            loss_infused_x = torch.nn.functional.cross_entropy(pred_infused_x, labels_infused_x)

                            total_loss += loss_attn_x + loss_infused_x

                            ffn_x_save = blk.forward_ffn(attn_x, H, W)
                            ffn_x_reshape = ffn_x_save.reshape(B, H, W, -1).permute(0, 3, 1, 2).contiguous()
                            down_ffn_x = nn.functional.adaptive_avg_pool2d(ffn_x_reshape, 7).permute(0, 2, 3, 1).contiguous().view(1,-1)
                            
                            x_ffn_infused = ffn_x_save + self.strainer2(self.norm2(attn_x), l=i, f=1)
                            
                            infused_ffn_x_reshape = x_ffn_infused.reshape(B, H, W, -1).permute(0, 3, 1, 2).contiguous()
                            down_infused_ffn_x = nn.functional.adaptive_avg_pool2d(infused_ffn_x_reshape, 7).permute(0, 2, 3, 1).contiguous().view(1,-1)

                            pred_ffn_x = self.classifier_block2_ffn(down_ffn_x)
                            pred_infused_x = self.classifier_block2_ffn(down_infused_ffn_x)
                            loss_ffn_x = torch.nn.functional.cross_entropy(pred_ffn_x, labels_ffn_x)
                            loss_infused_x = torch.nn.functional.cross_entropy(pred_infused_x, labels_infused_x)

                            total_loss += loss_ffn_x + loss_infused_x
                            x = ffn_x_save

                        elif discriminate == False:
                            x = blk.forward_attn(x, H, W) + self.strainer2(self.norm2(x), l=i, f=0)
                            x = blk.forward_ffn(x, H, W) + self.strainer2(self.norm2(x), l=i, f=1)
                    
                    elif inference == True:
                        x = blk.forward_attn(x, H, W)
                        x = blk.forward_ffn(x, H, W)




        x = self.norm2(x)
        x = x.reshape(B, H, W, -1).permute(0, 3, 1, 2).contiguous()
        outs.append(x)

        # stage 3
        x, H, W = self.patch_embed3(x)
        for i, blk in enumerate(self.block3):
            if img=='src':
                x = blk(x, H, W)
            elif img=='trg':
                if self.strainer3 is None:
                    x = blk(x, H, W)
                else:     
                    attn_x = blk.forward_attn(x, H, W)

                    if inference == False:
                        if discriminate == True:
                            attn_x = blk.forward_attn(x, H, W)
                            attn_x_reshape = attn_x.reshape(B, H, W, -1).permute(0, 3, 1, 2).contiguous()
                            down_attn_x = nn.functional.adaptive_avg_pool2d(attn_x_reshape, 7).permute(0, 2, 3, 1).contiguous().view(1,-1)
                            x_attn_infused = attn_x + self.strainer3(self.norm3(x), l=i, f=0)
                            infused_attn_x_reshape = x_attn_infused.reshape(B, H, W, -1).permute(0, 3, 1, 2).contiguous()
                            down_infused_x = nn.functional.adaptive_avg_pool2d(infused_attn_x_reshape, 7).permute(0, 2, 3, 1).contiguous().view(1,-1)
                            
                            pred_attn_x = self.classifier_block3_attn(down_attn_x)
                            pred_infused_x = self.classifier_block3_attn(down_infused_x)
                            loss_attn_x = torch.nn.functional.cross_entropy(pred_attn_x, labels_attn_x)
                            loss_infused_x = torch.nn.functional.cross_entropy(pred_infused_x, labels_infused_x)

                            total_loss += loss_attn_x + loss_infused_x

                            ffn_x_save = blk.forward_ffn(attn_x, H, W)
                            ffn_x_reshape = ffn_x_save.reshape(B, H, W, -1).permute(0, 3, 1, 2).contiguous()
                            down_ffn_x = nn.functional.adaptive_avg_pool2d(ffn_x_reshape, 7).permute(0, 2, 3, 1).contiguous().view(1,-1)
                            
                            x_ffn_infused = ffn_x_save + self.strainer3(self.norm3(attn_x), l=i, f=1)
                            
                            infused_ffn_x_reshape = x_ffn_infused.reshape(B, H, W, -1).permute(0, 3, 1, 2).contiguous()
                            down_infused_ffn_x = nn.functional.adaptive_avg_pool2d(infused_ffn_x_reshape, 7).permute(0, 2, 3, 1).contiguous().view(1,-1)

                            pred_ffn_x = self.classifier_block3_ffn(down_ffn_x)
                            pred_infused_x = self.classifier_block3_ffn(down_infused_ffn_x)
                            loss_ffn_x = torch.nn.functional.cross_entropy(pred_ffn_x, labels_ffn_x)
                            loss_infused_x = torch.nn.functional.cross_entropy(pred_infused_x, labels_infused_x)

                            total_loss += loss_ffn_x + loss_infused_x
                            x = ffn_x_save

                        elif discriminate == False:
                            x = blk.forward_attn(x, H, W) + self.strainer3(self.norm3(x), l=i, f=0)
                            x = blk.forward_ffn(x, H, W) + self.strainer3(self.norm3(x), l=i, f=1)
                    
                    elif inference == True:
                        x = blk.forward_attn(x, H, W)
                        x = blk.forward_ffn(x, H, W)

        x = self.norm3(x)
        x = x.reshape(B, H, W, -1).permute(0, 3, 1, 2).contiguous()
        outs.append(x)

        # stage 4
        x, H, W = self.patch_embed4(x)
        for i, blk in enumerate(self.block4):
            if img=='src':
                x = blk(x, H, W)
            elif img=='trg':
                if self.strainer4 is None:
                    x = blk(x, H, W)
                else:       
                    attn_x = blk.forward_attn(x, H, W)
                    
                    if inference == False:
                        if discriminate == True:
                            attn_x = blk.forward_attn(x, H, W)
                            attn_x_reshape = attn_x.reshape(B, H, W, -1).permute(0, 3, 1, 2).contiguous()
                            down_attn_x = nn.functional.adaptive_avg_pool2d(attn_x_reshape, 7).permute(0, 2, 3, 1).contiguous().view(1,-1)
                            x_attn_infused = attn_x + self.strainer4(self.norm4(x), l=i, f=0)
                            infused_attn_x_reshape = x_attn_infused.reshape(B, H, W, -1).permute(0, 3, 1, 2).contiguous()
                            down_infused_x = nn.functional.adaptive_avg_pool2d(infused_attn_x_reshape, 7).permute(0, 2, 3, 1).contiguous().view(1,-1)
                            
                            pred_attn_x = self.classifier_block4_attn(down_attn_x)
                            pred_infused_x = self.classifier_block4_attn(down_infused_x)
                            loss_attn_x = torch.nn.functional.cross_entropy(pred_attn_x, labels_attn_x)
                            loss_infused_x = torch.nn.functional.cross_entropy(pred_infused_x, labels_infused_x)

                            total_loss += loss_attn_x + loss_infused_x

                            ffn_x_save = blk.forward_ffn(attn_x, H, W)
                            ffn_x_reshape = ffn_x_save.reshape(B, H, W, -1).permute(0, 3, 1, 2).contiguous()
                            down_ffn_x = nn.functional.adaptive_avg_pool2d(ffn_x_reshape, 7).permute(0, 2, 3, 1).contiguous().view(1,-1)
                            
                            x_ffn_infused = ffn_x_save + self.strainer4(self.norm4(attn_x), l=i, f=1)
                            
                            infused_ffn_x_reshape = x_ffn_infused.reshape(B, H, W, -1).permute(0, 3, 1, 2).contiguous()
                            down_infused_ffn_x = nn.functional.adaptive_avg_pool2d(infused_ffn_x_reshape, 7).permute(0, 2, 3, 1).contiguous().view(1,-1)

                            pred_ffn_x = self.classifier_block4_ffn(down_ffn_x)
                            pred_infused_x = self.classifier_block4_ffn(down_infused_ffn_x)
                            loss_ffn_x = torch.nn.functional.cross_entropy(pred_ffn_x, labels_ffn_x)
                            loss_infused_x = torch.nn.functional.cross_entropy(pred_infused_x, labels_infused_x)

                            total_loss += loss_ffn_x + loss_infused_x
                            x = ffn_x_save

                        elif discriminate == False:
                            x = blk.forward_attn(x, H, W) + self.strainer4(self.norm4(x), l=i, f=0)
                            x = blk.forward_ffn(x, H, W) + self.strainer4(self.norm4(x), l=i, f=1)
                    
                    elif inference == True:
                        x = blk.forward_attn(x, H, W)
                        x = blk.forward_ffn(x, H, W)

        

        x = self.norm4(x)
        x = x.reshape(B, H, W, -1).permute(0, 3, 1, 2).contiguous()
        outs.append(x)

        return outs, total_loss

    def forward(self, x, img='trg', discriminate=False, inference=False):
        x = self.forward_features(x, img, discriminate, inference)

        return x
    
    # def nmi_score(self, features1, features2, temperature=0.1):
    #     bsz, seq_len, feat_dim = features1.shape
    #     features1 = features1.view(bsz * seq_len, feat_dim)
    #     features2 = features2.view(bsz * seq_len, feat_dim)
        
    #     logits = torch.mm(features1, features2.t()) 
    #     logits /= temperature
        
    #     labels = torch.arange(logits.size(0)).to(logits.device)
    #     loss = torch.nn.functional.cross_entropy(logits, labels)
    #     return loss

class DWConv(nn.Module):

    def __init__(self, dim=768):
        super(DWConv, self).__init__()
        self.dwconv = nn.Conv2d(dim, dim, 3, 1, 1, bias=True, groups=dim)

    def forward(self, x, H, W):
        B, N, C = x.shape
        x = x.transpose(1, 2).contiguous().view(B, C, H, W)
        x = self.dwconv(x)
        x = x.flatten(2).transpose(1, 2).contiguous()

        return x

class CLUB(nn.Module):  # CLUB: Mutual Information Contrastive Learning Upper Bound
    '''
        This class provides the CLUB estimation to I(X,Y)
        Method:
            forward() :      provides the estimation with input samples  
            loglikeli() :   provides the log-likelihood of the approximation q(Y|X) with input samples
        Arguments:
            x_dim, y_dim :         the dimensions of samples from X, Y respectively
            hidden_size :          the dimension of the hidden layer of the approximation network q(Y|X)
            x_samples, y_samples : samples from X and Y, having shape [sample_size, x_dim/y_dim] 
    '''
    def __init__(self, x_dim, y_dim, hidden_size):
        super(CLUB, self).__init__()
        # p_mu outputs mean of q(Y|X)
        #print("create CLUB with dim {}, {}, hiddensize {}".format(x_dim, y_dim, hidden_size))
        self.p_mu = nn.Sequential(nn.Linear(x_dim, hidden_size//2),
                                       nn.ReLU(),
                                       nn.Linear(hidden_size//2, y_dim))
        # p_logvar outputs log of variance of q(Y|X)
        self.p_logvar = nn.Sequential(nn.Linear(x_dim, hidden_size//2),
                                       nn.ReLU(),
                                       nn.Linear(hidden_size//2, y_dim),
                                       nn.Tanh())
        #                                nn.ReLU(),
        #                                nn.Linear(128, 32))

    def get_mu_logvar(self, x_samples):
        mu = self.p_mu(x_samples)
        logvar = self.p_logvar(x_samples)
        return mu, logvar
    
    def forward(self, x_samples, y_samples): 

        mu, logvar = self.get_mu_logvar(x_samples)
        
        # log of conditional probability of positive sample pairs
        positive = - (mu - y_samples)**2 /2./logvar.exp()  
        
        prediction_1 = mu.unsqueeze(1)          # shape [nsample,1,dim]
        y_samples_1 = y_samples.unsqueeze(0)    # shape [1,nsample,dim]

        # log of conditional probability of negative sample pairs
        negative = - ((y_samples_1 - prediction_1)**2).mean(dim=1)/2./logvar.exp() 

        return (positive.sum(dim = -1) - negative.sum(dim = -1)).mean()

    def loglikeli(self, x_samples, y_samples): # unnormalized loglikelihood 
        mu, logvar = self.get_mu_logvar(x_samples)
        return (-(mu - y_samples)**2 /logvar.exp()-logvar).sum(dim=1).mean(dim=0)
    
    def learning_loss(self, x_samples, y_samples):
        return - self.loglikeli(x_samples, y_samples)
